#  yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
#
# --- Linux ---
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
# echo 'command -v task >/dev/null || export PATH="$PATH:$HOME/.local/bin"' >> ~/.profile
# source ~/.profile
#
# ---  macOS ---
# brew install go-task/tap/go-task
---
version: "3"

vars:
  REPO: microsoft/CAIRA
  REPO_ABS_ROOT_PATH:
    sh: git rev-parse --show-toplevel
  CURRENT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  OS:
    sh: uname | tr '[:upper:]' '[:lower:]'
  ARCH:
    sh: uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/'

includes:
  internal:
    taskfile: .taskfiles/internal.yml
  sh:
    taskfile: .taskfiles/bash.yml
  gh:
    taskfile: .taskfiles/github.yml
  js:
    taskfile: .taskfiles/javascript.yml
  md:
    taskfile: .taskfiles/markdown.yml
  sec:
    taskfile: .taskfiles/security.yml
  spell:
    taskfile: .taskfiles/spell.yml
  skills:
    taskfile: .taskfiles/skills.yml
  tf:
    taskfile: .taskfiles/terraform.yml
  yml:
    taskfile: .taskfiles/yaml.yml
  site:
    taskfile: .taskfiles/site.yml

tasks:
  default:
    desc: Default task
    silent: true
    cmds:
      - cmd: task --list
        ignore_error: true

  tools:
    desc: Install tools
    cmds:
      - task: sh:tools
      - task: gh:tools
      - task: js:tools
      - task: md:tools
      - task: sec:tools
      - task: spell:tools
      - task: tf:tools
      - task: yml:tools
      - task: site:tools

  lint:
    desc: Lint files
    deps:
      - task: sh:lint
      - task: gh:lint
      - task: js:lint
      - task: md:lint
      - task: sec:lint
      - task: spell:lint
      - task: tf:lint
      - task: yml:lint

  test:
    desc: Run all tests
    cmds:
      - task: tf:test

  docs:
    desc: Generate documentation
    cmds:
      - task: tf:docs
      - task: spell:lint
      - task: md:lint

  clean:
    desc: Clean up files
    deps:
      - task: tf:clean
      - task: site:clean
